name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: guse-linux
          - os: windows-latest
            artifact_name: guse-windows
          - os: macos-latest
            artifact_name: guse-macos

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu,x86_64-pc-windows-msvc,x86_64-apple-darwin

      - name: Build
        run: cargo build --release

      - name: Prepare binary
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/release/guse.exe ${{ matrix.artifact_name }}.exe
          else
            cp target/release/guse ${{ matrix.artifact_name }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          if-no-files-found: error

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: binaries
          pattern: guse-*

      - name: List artifacts
        run: ls -la binaries/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Binaries

            - `guse-linux` - Linux binary
            - `guse-windows.exe` - Windows binary
            - `guse-macos` - macOS binary

            ## Installation

            ### macOS/Linux
            ```bash
            curl -L -o guse https://github.com/${{ github.repository }}/releases/latest/download/guse-${{ matrix.os == 'macos-latest' && 'macos' || 'linux' }}
            chmod +x guse
            sudo mv guse /usr/local/bin/  # optional
            ```

            ### Windows
            1. Download `guse-windows.exe` from the [latest release page](https://github.com/${{ github.repository }}/releases/latest)
            2. Save the file to your desired location
            3. Rename to `guse.exe` (optional)
            4. Add to PATH (optional)
          files: |
            binaries/guse-linux
            binaries/guse-windows.exe
            binaries/guse-macos
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
